CREATE TABLE `booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `zipcode` VARCHAR(45) NOT NULL,
  `type` ENUM('HOUSEKEEPING', 'DOG_WALK') NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`));
